"use client";

import { FormEvent, useMemo, useState } from "react";
import { rooms } from "@/data/rooms";

const money = new Intl.NumberFormat("ru-RU");
const today = new Date().toISOString().slice(0, 10);

export function Booking({ initialRoom }: { initialRoom?: string }) {
  const [roomSlug, setRoomSlug] = useState(initialRoom ?? "suite");
  const [checkIn, setCheckIn] = useState(""); const [checkOut, setCheckOut] = useState(""); const [guests, setGuests] = useState("2");
  const [step, setStep] = useState<"search" | "details" | "success">("search"); const [error, setError] = useState(""); const [sending, setSending] = useState(false); const [confirmation, setConfirmation] = useState("");
  const room = rooms.find((item) => item.slug === roomSlug) ?? rooms[0];
  const nights = useMemo(() => { if (!checkIn || !checkOut) return 1; return Math.max(1, Math.round((new Date(checkOut).getTime() - new Date(checkIn).getTime()) / 86400000)); }, [checkIn, checkOut]);
  const total = room.price * nights;
  function findRoom(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!checkIn || !checkOut || new Date(checkOut) <= new Date(checkIn)) { setError("Укажите корректные даты заезда и выезда."); return; } setError(""); setStep("details"); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (!String(data.get("name") ?? "").trim() || !String(data.get("phone") ?? "").trim() || !String(data.get("email") ?? "").includes("@")) { setError("Заполните имя, телефон и корректный email."); return; } setError(""); setSending(true); window.setTimeout(() => { setConfirmation(`CT-${Math.floor(100000 + Math.random() * 900000)}`); setSending(false); setStep("success"); }, 550); }
  if (step === "success") return <section className="booking-success" id="booking" aria-live="polite"><p className="section-kicker">Заявка принята</p><h2>До встречи<br /><i>в городе.</i></h2><p>Мы сохранили демо-заявку № {confirmation}. В настоящем проекте этот шаг подключается к PMS или CRM отеля.</p><dl><div><dt>Номер</dt><dd>{room.name}</dd></div><div><dt>Даты</dt><dd>{checkIn} — {checkOut}</dd></div><div><dt>Итого</dt><dd>≈ {money.format(total)} ₽</dd></div></dl><button className="button button-dark" type="button" onClick={() => setStep("search")}>Создать новую заявку</button></section>;
  return <section className="booking section" id="booking" aria-labelledby="booking-title"><div className="booking-intro"><p className="section-kicker">Demo booking</p><h2 className="section-title" id="booking-title">Номер уже<br /><i>ждёт вас.</i></h2><p>Это автономный демо-сценарий: без оплаты и передачи данных сторонним сервисам.</p><a href="tel:+74262240330" className="booking-call">Нужна помощь? Позвонить →</a></div><div className="booking-panel">{step === "search" ? <form onSubmit={findRoom} noValidate><div className="booking-panel-head"><span>01</span><h3>Даты и гости</h3></div><div className="booking-fields"><label>Заезд<input type="date" min={today} value={checkIn} onChange={(e) => setCheckIn(e.target.value)} required /></label><label>Выезд<input type="date" min={checkIn || today} value={checkOut} onChange={(e) => setCheckOut(e.target.value)} required /></label><label>Гости<select value={guests} onChange={(e) => setGuests(e.target.value)}><option value="1">1 гость</option><option value="2">2 гостя</option><option value="3">3 гостя</option></select></label></div>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary" type="submit">Найти номер <span>→</span></button></form> : <form onSubmit={submit} noValidate><div className="booking-panel-head"><span>02</span><h3>Детали заявки</h3><button type="button" className="text-button" onClick={() => setStep("search")}>Изменить</button></div><fieldset><legend>Выберите номер</legend><div className="room-picker">{rooms.map((item) => <label key={item.slug} className={roomSlug === item.slug ? "selected" : ""}><input type="radio" name="room" value={item.slug} checked={roomSlug === item.slug} onChange={() => setRoomSlug(item.slug)} /><span>{item.name}<small>{item.area} · от {money.format(item.price)} ₽</small></span></label>)}</div></fieldset><div className="guest-fields"><label>Ваше имя<input name="name" autoComplete="name" placeholder="Иван Петров" /></label><label>Телефон<input name="phone" type="tel" autoComplete="tel" placeholder="+7 000 000-00-00" /></label><label>Email<input name="email" type="email" autoComplete="email" placeholder="name@example.com" /></label><label>Комментарий<textarea name="comment" rows={2} placeholder="Например, поздний заезд" /></label></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="booking-submit"><p>{nights} {nights === 1 ? "ночь" : "ночей"} · ≈ <strong>{money.format(total)} ₽</strong></p><button className="button button-primary" type="submit" disabled={sending}>{sending ? "Отправляем…" : "Подтвердить заявку"} <span>→</span></button></div></form>}</div></section>;
}
