"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { galleryItems } from "@/data/site";

export function Gallery() {
  const [active, setActive] = useState<number | null>(null);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (active === null) return; if (event.key === "Escape") setActive(null); if (event.key === "ArrowRight") setActive((active + 1) % galleryItems.length); if (event.key === "ArrowLeft") setActive((active - 1 + galleryItems.length) % galleryItems.length); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [active]);
  return <section className="section gallery" id="gallery" aria-labelledby="gallery-title"><div className="section-head split-head"><div><p className="section-kicker">Взгляд изнутри</p><h2 className="section-title" id="gallery-title">Несколько<br /><i>точек тишины.</i></h2></div><p className="section-intro">Пространства для приезда, встречи, отдыха и утра без лишней спешки.</p></div><div className="gallery-grid">{galleryItems.map((item, index) => <button key={item.src} className={`gallery-item gallery-item-${index + 1}`} type="button" onClick={() => setActive(index)} aria-label={`Открыть фото: ${item.alt}`}><Image src={item.src} alt={item.alt} fill unoptimized sizes="(max-width: 760px) 100vw, 50vw" /><span>0{index + 1}</span></button>)}</div>{active !== null && <div className="lightbox" role="dialog" aria-modal="true" aria-label="Просмотр галереи" onClick={() => setActive(null)}><button className="lightbox-close" type="button" onClick={() => setActive(null)} aria-label="Закрыть галерею">×</button><button className="lightbox-prev" type="button" onClick={(event) => { event.stopPropagation(); setActive((active - 1 + galleryItems.length) % galleryItems.length); }} aria-label="Предыдущее фото">←</button><figure onClick={(event) => event.stopPropagation()}><Image src={galleryItems[active].src} alt={galleryItems[active].alt} fill unoptimized sizes="90vw" /><figcaption>{galleryItems[active].alt} · {active + 1} / {galleryItems.length}</figcaption></figure><button className="lightbox-next" type="button" onClick={(event) => { event.stopPropagation(); setActive((active + 1) % galleryItems.length); }} aria-label="Следующее фото">→</button></div>}</section>;
}
